Fixed yamllint warning and errors
cendio/ansible-role-thinlinc-server pull request #17
Opened 2021-02-16 22:30 UTC by pewo

Added a variable to fix yamllint error    `line too long (87 > 80 characters)  (line-length)`

```yaml
thinlinc_pack: "{{ thinlinc_version }}-{{ thinlinc_build }}"
```
And used that variable in all vars files

Fixed some other minor warnings  ` truthy value should be one of [false, true]  (truthy)`
```yaml
changed_when: False
changed_when: false
```
And some other warnings and errors:
`error    too many blank lines (1 > 0)  (empty-lines)`
`error    no new line character at the end of file  (new-line-at-end-of-file)`
`warning  missing document start "---"  (document-start)`

With these fixes yamllint reports nothing

2021-03-04 07:54 UTC, CendioOssman requested changes

2021-03-04 07:54 UTC, CendioOssman commented on defaults/main.yml
> +thinlinc_pack: "{{ thinlinc_version }}-{{ thinlinc_build }}"
Sorry for being unclear, but the goal was one commit per type of change. Not per file. So all of these would be in the same commit.

That said, I think these are just making it difficult to read. So I think we should disable this lint rule, at least for the constants that define the file names.

2021-03-04 07:54 UTC, CendioOssman commented on defaults/main.yml
> +"
Same thing here. This just makes it difficult to copy and paste things.

2021-03-04 22:04 UTC, pewo commented
Restarted from the 1.6 release,  added .yamllint file and fixed small things like newline/blank lines/---.
yamllint does not report any warnings or errors.

2021-03-16 12:24 UTC, CendioOssman commented
Great, thanks.

2021-03-16 12:24 UTC, merged